# Generated by Django 5.2.1 on 2025-05-30 20:21

from django.db import migrations, models

import django_params_field.params_field


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelForTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params_field_default",
                    django_params_field.params_field.ParamsField(params_type=None),
                ),
            ],
        ),
    ]
